com331_project1-master 2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :complaints, only: [:index, :new, :create, :show]

  root 'complaints#index'
end

com331_project1-master 2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

com331_project1-master 2/app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :reporter

  validates :date, :location, :department, :description, :reporter_id, presence: true

  validates :department, inclusion: { in: %w(Maintenance Technology),
    message: "- you did not enter a valid department" }

  validates :location, inclusion: {
    in: %w(Stuart Keating Kaplan Pritzker Engineering Alumni  Hermann MSV SSV MTCC
      Perlstein Wishnick Siegel Galvin Crown IIT-Tower),
      message: "- you did not enter a valid location"  }

  def person_number=(a_number)
    self.reporter = Reporter.find_by(a_number: a_number)
  end

  def person_number
    self.reporter ? self.reporter.a_number : nil
  end

  #def validate(record)
  #unless Reporter.find_by_a_number(record.a_number)
    #record.errors[:a_number] << 'Student ID is missing from database'
    #end
  #end

end

com331_project1-master 2/app/models/reporter.rb
class Reporter < ApplicationRecord
  has_many :complaints

  validates :first_name, :last_name, :a_number, :school_email, presence: true

  validates :a_number, uniqueness: true

  validates :school_email, uniqueness: true

  validates :school_email,
  format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    message: 'must be in the email format.'
  }

end

com331_project1-master 2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

com331_project1-master 2/app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params

      params.require(:complaint).permit(:date, :location, :department, :description, :person_number)
    end
end

com331_project1-master 2/app/helpers/application_helper.rb
module ApplicationHelper
end

com331_project1-master 2/app/helpers/complaints_helper.rb
module ComplaintsHelper
end

com331_project1-master 2/app/views/complaints/_form.html.haml
= form_for @complaint do |f|
  - if @complaint.errors.any?
    #error_explanation
      %h3= "#{pluralize(@complaint.errors.count, "error")} prohibited this complaint from being saved:"
      %ul
        - @complaint.errors.full_messages.each do |message|
          %li#error= message

  %ol.inputs
    %li
      = f.label :date, "Date"
      = f.date_field :date
    %li
      = f.label :location, "Location"
      = f.select :location, [' ', 'Stuart', 'Keating', 'Kaplan', 'Pritzker', 'Engineering',
      'Alumni', 'Hermann', 'MSV', 'SSV', 'MTCC', 'Perlstein', 'Wishnick', 'Siegel', 'Galvin', 'Crown', 'IIT-Tower' ]

    %li
      = f.label :department, "Department for complaint"
      = f.select :department, [' ', 'Maintenance', 'Technology']
    %li
      = f.label :description, "Description"
      = f.text_area :description
    %li
      = f.label :ID, "ID number"
      = f.number_field :person_number

    %li.actions
      = f.submit 'Save'

com331_project1-master 2/app/views/complaints/edit.html.haml
%h1 Editing complaint

= render 'form'

%footer
 %ul.controls
  %li= link_to 'Show', @complaint
  %li= link_to 'Back', complaints_path

com331_project1-master 2/app/views/complaints/index.html.haml
%header
  %p= link_to 'Create New Complaint', new_complaint_path

%h2 Newest Complaints
%ul.complaints
  - @complaints.each do |complaint|
    %li
      %article
        %h3= complaint.description
        %ul.info
          %ul= "Date: #{complaint.date}"

        %ul.controls#index
          %ul= link_to 'Details', complaint

com331_project1-master 2/app/views/complaints/new.html.haml
%h1 New complaint

= render 'form'

%footer
 %ul.controls
  %li#back= link_to 'Back', complaints_path

com331_project1-master 2/app/views/complaints/show.html.haml
%p#notice= notice

%article
  %h3= "Details of Complaint"
  %p.byline= "Report Number: #{@complaint.reporter_id}"
  %p.byline= "Date: #{@complaint.date}"
  %p.byline= "Location: #{@complaint.location}"
  %p.byline= "Department: #{@complaint.department}"
  %p.byline= "Description: #{@complaint.description}"

%footer
  %ul.controls
    %li#back= link_to 'Back', complaints_path

com331_project1-master 2/app/views/layouts/application.html.haml
!!!5
%html{lang: "en"}
  %head
    %meta{charset: "UTF-8"}
    %title Com331Project1
    %meta{name: "viewport", content: "width=device-width,initial-scale=1.0,shrink-to-fit=no"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %body

      %header#header
        %h1 IIT Complaints
        %p.tagline We are here to listen!
        = yield

    %footer#footer
      %small by Jessica DeJesus